/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CumInvatamRouteImport } from './routes/cum-invatam'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ResurseRouteImport } from './routes/resurse'
import { Route as SigurantaRouteImport } from './routes/siguranta'
import { Route as TransparentaRouteImport } from './routes/transparenta'
import { Route as ExperienteIndexRouteImport } from './routes/experiente.index'
import { Route as ExperienteSlugRouteImport } from './routes/experiente.$slug'
import { Route as ImplicaTeIndexRouteImport } from './routes/implica-te.index'
import { Route as ImplicaTeDoneazaRouteImport } from './routes/implica-te.doneaza'
import { Route as ImplicaTeOferaOExperientaRouteImport } from './routes/implica-te.ofera-o-experienta'
import { Route as ImplicaTeParteneriRouteImport } from './routes/implica-te.parteneri'
import { Route as ImplicaTeVoluntariatRouteImport } from './routes/implica-te.voluntariat'
import { Route as LegalConfidentialitateRouteImport } from './routes/legal.confidentialitate'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalGdprRouteImport } from './routes/legal.gdpr'
import { Route as LegalProtectiaCopiluluiRouteImport } from './routes/legal.protectia-copilului'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CumInvatamRoute = CumInvatamRouteImport.update({
  id: '/cum-invatam',
  path: '/cum-invatam',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResurseRoute = ResurseRouteImport.update({
  id: '/resurse',
  path: '/resurse',
  getParentRoute: () => rootRouteImport,
} as any)
const SigurantaRoute = SigurantaRouteImport.update({
  id: '/siguranta',
  path: '/siguranta',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparentaRoute = TransparentaRouteImport.update({
  id: '/transparenta',
  path: '/transparenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienteIndexRoute = ExperienteIndexRouteImport.update({
  id: '/experiente/',
  path: '/experiente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienteSlugRoute = ExperienteSlugRouteImport.update({
  id: '/experiente/$slug',
  path: '/experiente/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicaTeIndexRoute = ImplicaTeIndexRouteImport.update({
  id: '/implica-te/',
  path: '/implica-te/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicaTeDoneazaRoute = ImplicaTeDoneazaRouteImport.update({
  id: '/implica-te/doneaza',
  path: '/implica-te/doneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicaTeOferaOExperientaRoute =
  ImplicaTeOferaOExperientaRouteImport.update({
    id: '/implica-te/ofera-o-experienta',
    path: '/implica-te/ofera-o-experienta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImplicaTeParteneriRoute = ImplicaTeParteneriRouteImport.update({
  id: '/implica-te/parteneri',
  path: '/implica-te/parteneri',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicaTeVoluntariatRoute = ImplicaTeVoluntariatRouteImport.update({
  id: '/implica-te/voluntariat',
  path: '/implica-te/voluntariat',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialitateRoute = LegalConfidentialitateRouteImport.update({
  id: '/legal/confidentialitate',
  path: '/legal/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalGdprRoute = LegalGdprRouteImport.update({
  id: '/legal/gdpr',
  path: '/legal/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalProtectiaCopiluluiRoute = LegalProtectiaCopiluluiRouteImport.update({
  id: '/legal/protectia-copilului',
  path: '/legal/protectia-copilului',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cum-invatam': typeof CumInvatamRoute
  '/despre': typeof DespreRoute
  '/galerie': typeof GalerieRoute
  '/impact': typeof ImpactRoute
  '/resurse': typeof ResurseRoute
  '/siguranta': typeof SigurantaRoute
  '/transparenta': typeof TransparentaRoute
  '/experiente/$slug': typeof ExperienteSlugRoute
  '/implica-te/doneaza': typeof ImplicaTeDoneazaRoute
  '/implica-te/ofera-o-experienta': typeof ImplicaTeOferaOExperientaRoute
  '/implica-te/parteneri': typeof ImplicaTeParteneriRoute
  '/implica-te/voluntariat': typeof ImplicaTeVoluntariatRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/protectia-copilului': typeof LegalProtectiaCopiluluiRoute
  '/experiente/': typeof ExperienteIndexRoute
  '/implica-te/': typeof ImplicaTeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cum-invatam': typeof CumInvatamRoute
  '/despre': typeof DespreRoute
  '/galerie': typeof GalerieRoute
  '/impact': typeof ImpactRoute
  '/resurse': typeof ResurseRoute
  '/siguranta': typeof SigurantaRoute
  '/transparenta': typeof TransparentaRoute
  '/experiente/$slug': typeof ExperienteSlugRoute
  '/implica-te/doneaza': typeof ImplicaTeDoneazaRoute
  '/implica-te/ofera-o-experienta': typeof ImplicaTeOferaOExperientaRoute
  '/implica-te/parteneri': typeof ImplicaTeParteneriRoute
  '/implica-te/voluntariat': typeof ImplicaTeVoluntariatRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/protectia-copilului': typeof LegalProtectiaCopiluluiRoute
  '/experiente': typeof ExperienteIndexRoute
  '/implica-te': typeof ImplicaTeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cum-invatam': typeof CumInvatamRoute
  '/despre': typeof DespreRoute
  '/galerie': typeof GalerieRoute
  '/impact': typeof ImpactRoute
  '/resurse': typeof ResurseRoute
  '/siguranta': typeof SigurantaRoute
  '/transparenta': typeof TransparentaRoute
  '/experiente/$slug': typeof ExperienteSlugRoute
  '/implica-te/doneaza': typeof ImplicaTeDoneazaRoute
  '/implica-te/ofera-o-experienta': typeof ImplicaTeOferaOExperientaRoute
  '/implica-te/parteneri': typeof ImplicaTeParteneriRoute
  '/implica-te/voluntariat': typeof ImplicaTeVoluntariatRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/protectia-copilului': typeof LegalProtectiaCopiluluiRoute
  '/experiente/': typeof ExperienteIndexRoute
  '/implica-te/': typeof ImplicaTeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cum-invatam'
    | '/despre'
    | '/galerie'
    | '/impact'
    | '/resurse'
    | '/siguranta'
    | '/transparenta'
    | '/experiente/$slug'
    | '/implica-te/doneaza'
    | '/implica-te/ofera-o-experienta'
    | '/implica-te/parteneri'
    | '/implica-te/voluntariat'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/protectia-copilului'
    | '/experiente/'
    | '/implica-te/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cum-invatam'
    | '/despre'
    | '/galerie'
    | '/impact'
    | '/resurse'
    | '/siguranta'
    | '/transparenta'
    | '/experiente/$slug'
    | '/implica-te/doneaza'
    | '/implica-te/ofera-o-experienta'
    | '/implica-te/parteneri'
    | '/implica-te/voluntariat'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/protectia-copilului'
    | '/experiente'
    | '/implica-te'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cum-invatam'
    | '/despre'
    | '/galerie'
    | '/impact'
    | '/resurse'
    | '/siguranta'
    | '/transparenta'
    | '/experiente/$slug'
    | '/implica-te/doneaza'
    | '/implica-te/ofera-o-experienta'
    | '/implica-te/parteneri'
    | '/implica-te/voluntariat'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/protectia-copilului'
    | '/experiente/'
    | '/implica-te/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CumInvatamRoute: typeof CumInvatamRoute
  DespreRoute: typeof DespreRoute
  GalerieRoute: typeof GalerieRoute
  ImpactRoute: typeof ImpactRoute
  ResurseRoute: typeof ResurseRoute
  SigurantaRoute: typeof SigurantaRoute
  TransparentaRoute: typeof TransparentaRoute
  ExperienteSlugRoute: typeof ExperienteSlugRoute
  ImplicaTeDoneazaRoute: typeof ImplicaTeDoneazaRoute
  ImplicaTeOferaOExperientaRoute: typeof ImplicaTeOferaOExperientaRoute
  ImplicaTeParteneriRoute: typeof ImplicaTeParteneriRoute
  ImplicaTeVoluntariatRoute: typeof ImplicaTeVoluntariatRoute
  LegalConfidentialitateRoute: typeof LegalConfidentialitateRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalGdprRoute: typeof LegalGdprRoute
  LegalProtectiaCopiluluiRoute: typeof LegalProtectiaCopiluluiRoute
  ExperienteIndexRoute: typeof ExperienteIndexRoute
  ImplicaTeIndexRoute: typeof ImplicaTeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cum-invatam': {
      id: '/cum-invatam'
      path: '/cum-invatam'
      fullPath: '/cum-invatam'
      preLoaderRoute: typeof CumInvatamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resurse': {
      id: '/resurse'
      path: '/resurse'
      fullPath: '/resurse'
      preLoaderRoute: typeof ResurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siguranta': {
      id: '/siguranta'
      path: '/siguranta'
      fullPath: '/siguranta'
      preLoaderRoute: typeof SigurantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparenta': {
      id: '/transparenta'
      path: '/transparenta'
      fullPath: '/transparenta'
      preLoaderRoute: typeof TransparentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiente/': {
      id: '/experiente/'
      path: '/experiente'
      fullPath: '/experiente/'
      preLoaderRoute: typeof ExperienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiente/$slug': {
      id: '/experiente/$slug'
      path: '/experiente/$slug'
      fullPath: '/experiente/$slug'
      preLoaderRoute: typeof ExperienteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implica-te/': {
      id: '/implica-te/'
      path: '/implica-te'
      fullPath: '/implica-te/'
      preLoaderRoute: typeof ImplicaTeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implica-te/doneaza': {
      id: '/implica-te/doneaza'
      path: '/implica-te/doneaza'
      fullPath: '/implica-te/doneaza'
      preLoaderRoute: typeof ImplicaTeDoneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implica-te/ofera-o-experienta': {
      id: '/implica-te/ofera-o-experienta'
      path: '/implica-te/ofera-o-experienta'
      fullPath: '/implica-te/ofera-o-experienta'
      preLoaderRoute: typeof ImplicaTeOferaOExperientaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implica-te/parteneri': {
      id: '/implica-te/parteneri'
      path: '/implica-te/parteneri'
      fullPath: '/implica-te/parteneri'
      preLoaderRoute: typeof ImplicaTeParteneriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implica-te/voluntariat': {
      id: '/implica-te/voluntariat'
      path: '/implica-te/voluntariat'
      fullPath: '/implica-te/voluntariat'
      preLoaderRoute: typeof ImplicaTeVoluntariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialitate': {
      id: '/legal/confidentialitate'
      path: '/legal/confidentialitate'
      fullPath: '/legal/confidentialitate'
      preLoaderRoute: typeof LegalConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/gdpr': {
      id: '/legal/gdpr'
      path: '/legal/gdpr'
      fullPath: '/legal/gdpr'
      preLoaderRoute: typeof LegalGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/protectia-copilului': {
      id: '/legal/protectia-copilului'
      path: '/legal/protectia-copilului'
      fullPath: '/legal/protectia-copilului'
      preLoaderRoute: typeof LegalProtectiaCopiluluiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CumInvatamRoute: CumInvatamRoute,
  DespreRoute: DespreRoute,
  GalerieRoute: GalerieRoute,
  ImpactRoute: ImpactRoute,
  ResurseRoute: ResurseRoute,
  SigurantaRoute: SigurantaRoute,
  TransparentaRoute: TransparentaRoute,
  ExperienteSlugRoute: ExperienteSlugRoute,
  ImplicaTeDoneazaRoute: ImplicaTeDoneazaRoute,
  ImplicaTeOferaOExperientaRoute: ImplicaTeOferaOExperientaRoute,
  ImplicaTeParteneriRoute: ImplicaTeParteneriRoute,
  ImplicaTeVoluntariatRoute: ImplicaTeVoluntariatRoute,
  LegalConfidentialitateRoute: LegalConfidentialitateRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalGdprRoute: LegalGdprRoute,
  LegalProtectiaCopiluluiRoute: LegalProtectiaCopiluluiRoute,
  ExperienteIndexRoute: ExperienteIndexRoute,
  ImplicaTeIndexRoute: ImplicaTeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
